In [2]:
import numpy as np
a=np.arange(0,9)
a.resize((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
d=np.delete(arr,[3,4,5])
d.resize((2,3))
d

array([[1, 2, 3],
       [7, 8, 9]])

In [3]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
d=arr[1,:]
d

array([4, 5, 6])

In [8]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=arr1 @ arr2
arr

32

In [9]:
a=np.random.rand(5,5)
print(a)
Mean=np.mean(a)
print('Mean is: ',Mean)
SD=np.std(a)
print('Std is: ',SD)

[[0.42747687 0.67066089 0.54501222 0.8686212  0.13007211]
 [0.90384011 0.24144759 0.01636185 0.48999937 0.79470424]
 [0.28690894 0.82211413 0.21698613 0.42245947 0.33700626]
 [0.1881439  0.43726917 0.25644755 0.72205321 0.04828195]
 [0.004933   0.09380671 0.66833497 0.95915694 0.69913246]]
Mean is:  0.4500492497140599
Std is:  0.2940857190600299
