### Exercise 2

### 1

In [1]:
import numpy as np
arr=np.array([12,15,17,19,20])
mean_arr=np.mean(arr)
median_arr=np.median(arr)
standard_deviation_arr=np.std(arr)
print("Mean: ",mean_arr)
print("Median: ",median_arr)
print("Standard deviation: ",standard_deviation_arr)

Mean:  16.6
Median:  17.0
Standard deviation:  2.870540018881465


### 2        

In [2]:
mat=np.array([[1,2],[3,4]])
determinant=np.linalg.det(mat)
print("Determinant is: ",determinant)

Determinant is:  -2.0000000000000004


### 3

In [2]:
random_intgrs=np.random.randint(0,101,size=10)
print(random_intgrs)

[91  6 19 91 45 79 93  1 67  2]


### 4

In [4]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
mltplctn=np.dot(A,B)
print(mltplctn)

[[19 22]
 [43 50]]


In [5]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
mltplctn=A @ B
print(mltplctn)

[[19 22]
 [43 50]]


### 5

In [6]:
def is_prime(number):
    if number<2:
        return False  
    i=2
    f=0
    while i<=number/2:
        if number % i == 0:
            f=1
            break
        i+=1
    if f==0:
        return True
    else:
        return False
primes=np.array([number for number in range(1,51) if is_prime(number)])  
print("prime numbers b/w 1 & 50 is: ",primes)
       

prime numbers b/w 1 & 50 is:  [ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47]


### 6

#### x normalized=x-mean(x) /std(x)

In [8]:
org_arr=np.array([10,20,30,40,50])
mean_arr=np.mean(org_arr)
std_arr=np.std(org_arr)
normalized_arr=(org_arr - mean_arr)/std_arr
print(normalized_arr)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### 7

In [7]:
arr=np.array([2,5,8,11,14,17,20,23])
odd_num=arr[arr %2!=0]
print(odd_num)

[ 5 11 17 23]


### 8

In [11]:
arr=np.arange(1,11)
sqrt_values=np.sqrt(arr)
print(sqrt_values)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


### 9

In [2]:
matrix=np.arange(9).reshape(3,3)
diagonal_elements=np.diag(matrix)
print(matrix)
print("/n",diagonal_elements)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
/n [0 4 8]


### 10

In [13]:
a=np.array([2,3,4,5])
b=np.array([10,20,30,40])
dot_prdct=np.dot(a,b)
print(dot_prdct)

400
