### Exercise 1

### 1

In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
a_reshape=a.reshape(3,3)
a_reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 2

In [4]:
b=np.array([5,6,7,8,9,10,11,12,13])
b_reshape=b.reshape(3,3)
b_reshape

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

### 3

In [5]:
result=a_reshape @ b_reshape
result

array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]])

### 4

In [6]:
dot_product=np.dot(a_reshape[0,:],b_reshape[:,0])
dot_product

54

### 5

In [10]:
sum_a=np.sum(a_reshape)
sum_a

45

In [13]:
a_reshape.sum()

45

### 6

In [12]:
prdct_b=np.prod(b_reshape)
prdct_b

259459200

In [14]:
b_reshape.prod()

259459200

### 7

In [8]:
c=np.array([1,2,3,4,5])
c

array([1, 2, 3, 4, 5])

In [9]:
I=np.insert(c,2,0)
I

array([1, 2, 0, 3, 4, 5])

### 8

In [10]:
d=np.array([1,2,3,4,5])
d

array([1, 2, 3, 4, 5])

In [11]:
D=np.delete(d,3)
D

array([1, 2, 3, 5])

### 9

In [12]:
e=np.array([[1,2,3,4],
           [5,6,7,8],
           [9,10,11,12]])
e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
select=e[e > 5]
print(select)

[ 6  7  8  9 10 11 12]


### 10

In [17]:
f=np.array([[1,2,3,4,5],
           [6,7,8,9,10],
           [11,12,13,14,15],
          [16,17,18,19,20]])
f

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
select_p=f[[0,1,2],[0,2,4]]
print(select_p)

[ 1  8 15]


### 11

In [1]:
import numpy as np
a=np.eye(5) * 0.5                 #np.eye() create a 2D identity matrix all diagonal elements are 1 and a;; other elements are 0
a                             

array([[0.5, 0. , 0. , 0. , 0. ],
       [0. , 0.5, 0. , 0. , 0. ],
       [0. , 0. , 0.5, 0. , 0. ],
       [0. , 0. , 0. , 0.5, 0. ],
       [0. , 0. , 0. , 0. , 0.5]])

### 12

In [21]:
b=np.random.randint(0,11,size=(3,3,3))
b

array([[[ 4,  3,  5],
        [ 5,  5,  5],
        [ 1,  2,  8]],

       [[ 5,  2, 10],
        [ 6,  5,  2],
        [ 0,  7,  6]],

       [[ 4, 10,  9],
        [ 2,  0, 10],
        [ 6,  2,  7]]])

### 13

In [22]:
row_mean=np.mean(b,axis=2)
print(row_mean)

[[4.         5.         3.66666667]
 [5.66666667 4.33333333 4.33333333]
 [7.66666667 4.         5.        ]]


### 14

In [6]:
a=np.eye(5) * 0.5
std_column=np.std(a,axis=0)
print(std_column)

[0.2 0.2 0.2 0.2 0.2]


### 15

In [7]:
a=np.eye(5) * 0.5
multplctn=np.dot(a,a.T)
print(multplctn)

[[0.25 0.   0.   0.   0.  ]
 [0.   0.25 0.   0.   0.  ]
 [0.   0.   0.25 0.   0.  ]
 [0.   0.   0.   0.25 0.  ]
 [0.   0.   0.   0.   0.25]]


### 16

In [13]:
c=np.eye(6)
print("Array is: ")
print(c)
c_shift=np.roll(c,1,axis=1)
print("Array after shifting values to right by one position: ")
print(c_shift)

Array is: 
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Array after shifting values to right by one position: 
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]]


### 17

In [17]:
d=np.random.rand(4,4)
print("Array is: ")
print(d)
d_normalized=d/ d.sum(axis=1,keepdims=True)
print("Array after normalization each row sums to 1:  ")
print(d_normalized)

Array is: 
[[0.25103405 0.96824045 0.36075336 0.30112695]
 [0.59542248 0.06902412 0.18819881 0.66917651]
 [0.13097373 0.73591108 0.73298072 0.13904292]
 [0.20552069 0.76204509 0.51390591 0.39098744]]
Array after normalization each row sums to 1:  
[[0.13344678 0.51470535 0.19177229 0.16007558]
 [0.39125635 0.04535624 0.12366677 0.43972064]
 [0.07531951 0.42320289 0.42151772 0.07995988]
 [0.10975977 0.40697555 0.27445507 0.2088096 ]]


### 18

In [16]:
e=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array is: ")
print(e)
e_flip=np.flipud(e)
print("After flipping vertically: ")
print(e_flip)



Array is: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After flipping vertically: 
[[7 8 9]
 [4 5 6]
 [1 2 3]]


### 19

In [25]:
f=np.random.randint(0,11,size=(4,4))
f

array([[9, 7, 6, 6],
       [2, 2, 5, 3],
       [9, 2, 2, 3],
       [8, 6, 9, 0]])

In [28]:
sort_row=np.sort(f,axis=1)
print(sort_row)

[[6 6 7 9]
 [2 2 3 5]
 [2 2 3 9]
 [0 6 8 9]]


### 20

In [8]:
import numpy as np
g = np.ones((5, 5)) - np.eye(5)
g_inv = np.linalg.inv(g)
print("Original Matrix:")
print(g)
print("Inverse Matrix:")
print(g_inv)


Original Matrix:
[[0. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 0.]]
Inverse Matrix:
[[-0.75  0.25  0.25  0.25  0.25]
 [ 0.25 -0.75  0.25  0.25  0.25]
 [ 0.25  0.25 -0.75  0.25  0.25]
 [ 0.25  0.25  0.25 -0.75  0.25]
 [ 0.25  0.25  0.25  0.25 -0.75]]
