### NumPy
#### (Numerical Python)
### fast computation with n-dimensional arrays
### Based around one data structure
### ndarray - n-dimensional array

#### Usage is np.command(xxx)

In [1]:
!pip3 install numpy

### How to import Numpy

In [2]:
import numpy

In [2]:
import numpy as np

#### An array is usually a fixed size container of items of the same tyoe and size.

### Difference b/w python list and a NumPy array
#### Numpy fast and efficient way of creating arrays
#### list contain different data types in a single list
#### all elements in a numpy array are homogeneous

### Nested list

In [4]:

list1=[1,2,3,4,5]
print(type(list1))
print(list1)

<class 'list'>
[1, 2, 3, 4, 5]


In [5]:
a=np.array(list1)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [6]:
a=np.array([1,2,3,4])
print(type(a))
tup=(4,5,6)
a=np.array(tup)
print(type(a))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [7]:
### two dimensional array creation
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[1][1])
print(type(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
<class 'numpy.ndarray'>


### N-dimensional array
  #### An N-dimensional array is simply an array with any no.of dimensions.    

#### 1-D
#### 2-D and so on
#### Numpy ndarray is used to represent both matrices and vectors.

#### vector is an array with a single dimension (no diiference b/w row and column)

#### Matrix refers to an array of 2 dimensions.

#### 3-D or higher dimensional arrays ,the term tensor is. commonly used


### Attributes of an array

#### the no.of dimensions and items in an array is defined by its shape.
#### in numpy dimensionns are called axes.

### Basic arrays

#### np.array()
#### np.zeros()
#### np.ones()
#### np.empty()
#### np.arange()
#### np.linspace()
#### dtype

In [8]:

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones((6,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
### create an array with a range of elements
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [14]:
np.linspace(0, 10, num=3)

array([ 0.,  5., 10.])

### Adding removing sorting elements.

#### np.sort()

In [16]:

arr=np.array([5,3,7,1,8,9,10])
np.sort(arr)

array([ 1,  3,  5,  7,  8,  9, 10])

#### argsort : indirect sort along a specified axis
#### lexsort : indirect stable sort on multiple keys
#### searchsorted : find elements in a sorted array
#### partition : partial sort

#### np.argsort()

#### numpy.argsort(a, axis=-1, kind=None, order=None)


In [21]:
a=np.array([3, 1, 2])
sorted_indices=np.argsort(a)                       #1d
print(sorted_indices)

[1 2 0]


In [22]:
a=np.array([3,1,2])
np.argsort(a)

array([1, 2, 0], dtype=int64)

In [4]:
x = np.array([[0, 3], [2, 2]])
x                                                #2d

array([[0, 3],
       [2, 2]])

In [5]:
ind = np.argsort(x, axis=0)  # sorts along first axis (down)
np.take_along_axis(x, ind, axis=0)  # same as np.sort(x, axis=0)


array([[0, 2],
       [2, 3]])

In [8]:
ind = np.argsort(x, axis=1)  # sorts along last axis (across)
np.take_along_axis(x, ind, axis=1)  # same as np.sort(x, axis=1)


array([[0, 3],
       [2, 2]])

In [13]:
x = np.array([[3, 1], [4, 2]])
ind = np.unravel_index(np.argsort(x, axis=None), x.shape)

sorted_x = x[ind]
sorted_x_using_sort = np.sort(x, axis=None)

print("Using indices:", sorted_x)
print("Using np.sort:", sorted_x_using_sort)

Using indices: [1 2 3 4]
Using np.sort: [1 2 3 4]


#### np.lexsort()
#### numpy.lexsort(keys, axis=-1)

In [24]:
## sort first by surname then by name
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')      
ind = np.lexsort((first_names, surnames))
print(ind)

[1 2 0]


In [25]:
[surnames[i] + ", " + first_names[i] for i in ind]

['Galilei, Galileo', 'Hertz, Gustav', 'Hertz, Heinrich']

In [ ]:
# Sort two columns of numbers:

In [26]:
a = [1,5,1,4,3,4,4] # First column
b = [9,4,0,4,0,2,1] # Second column
ind = np.lexsort((b,a)) # Sort by a, then by b
ind

array([2, 0, 4, 6, 5, 3, 1], dtype=int64)

In [27]:
[(a[i],b[i]) for i in ind]

[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]

#### np.searchsorted()
#### numpy.searchsorted(a, v, side='left', sorter=None)

In [28]:
np.searchsorted([1,2,3,4,5], 3)

2

In [31]:
np.searchsorted([1,2,3,4,5], 3, side='right')

3

In [32]:
np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3])

array([0, 5, 1, 2], dtype=int64)

#### np.partition()
#### numpy.partition(a, kth, axis=-1, kind='introselect', order=None)

In [33]:
a = np.array([7, 1, 7, 7, 1, 5, 7, 2, 3, 2, 6, 2, 3, 0])
p = np.partition(a, 4)
p

array([0, 1, 2, 1, 2, 5, 2, 3, 3, 6, 7, 7, 7, 7])

In [36]:
p2 = np.partition(a, (4, 8))
p2

array([0, 1, 2, 1, 2, 3, 3, 2, 5, 6, 7, 7, 7, 7])

In [39]:
a=np.array([[3,1,4],[1,9,5],[2,5,6]])
p=np.partition(a,1,axis=1)
p


array([[1, 3, 4],
       [1, 5, 9],
       [2, 5, 6]])

In [40]:
a=np.array([10,8,6,4,2,0,9,7,5,3,1])
p=np.partition(a,5)
print("origina array",a)
print("partitioned array",p)

origina array [10  8  6  4  2  0  9  7  5  3  1]
partitioned array [ 0  1  4  3  2  5  6  7  8  9 10]


### np.concatenate()

In [17]:

import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
print(x)
print("-------")
print(y)
print("--------")
print(y.T)          #transpose
print("--------")
print(np.concatenate((x,y),axis=0))
print("--------")
print(np.concatenate((x,y.T),axis=1))

[[1 2]
 [3 4]]
-------
[[5 6]]
--------
[[5]
 [6]]
--------
[[1 2]
 [3 4]
 [5 6]]
--------
[[1 2 5]
 [3 4 6]]


#### ndarray.ndim : tell you the no.of axes or dimensions of the array.
#### ndarray.size : total no.of elements of the array.
#### ndarray.shape : display a tuple of integers that indicate the no.of elements stored along each dimension of the array.for eg: you have a 2-D array with 2 rows and 3 columns, the shpe of the array is (2,3)

In [19]:
### 3d
array_example=np.array([[[0,1,2,4,3],
                        [4,5,6,7,4]],
                       [[0,1,2,3,4],
                       [4,5,6,7,5]],
                       [[0,1,2,3,6],
                       [4,5,6,7,9]],
                       ])
print(array_example)

[[[0 1 2 4 3]
  [4 5 6 7 4]]

 [[0 1 2 3 4]
  [4 5 6 7 5]]

 [[0 1 2 3 6]
  [4 5 6 7 9]]]


In [20]:
array_example.ndim

3

In [21]:
array_example.size

30

In [22]:
array_example.shape

(3, 2, 5)

#### Reshape

In [3]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [4]:
b=a.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [5]:
a=np.arange(6)
b=a.reshape((3,2))
print(b)

[[0 1]
 [2 3]
 [4 5]]


#### Resize

In [6]:
arr=np.array([1,2,3,4,5,6])
arr.resize((2,3))
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
arr=np.array([1,2,3,4,5,6])
arr.resize((3,4))
print(arr)

[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


#### np.newaxis will increase the dimension of array by one dimension when used once.ie; 1d array will be 2d array

In [8]:
a=np.array([1,2,3,4,5,6])
print(a)
print(a.shape)
print(a.ndim)

[1 2 3 4 5 6]
(6,)
1


In [9]:
a2=a[np.newaxis, :]
print(a2)
print(a2.shape)
print(a2.ndim)

[[1 2 3 4 5 6]]
(1, 6)
2


In [11]:
a3=a2[np.newaxis, :]
print(a3)
print(a3.shape)
print(a3.ndim)

[[[1 2 3 4 5 6]]]
(1, 1, 6)
3


In [12]:
col_vector=a[: ,np.newaxis]
col_vector.shape
print(col_vector)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


#### indexing and slicing

In [2]:
import numpy as np
data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
data[1:6]

array([1, 2, 3, 4, 5])

In [3]:
data[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
data[-2:]

array([8, 9])

In [5]:
data[:3]

array([0, 1, 2])

In [13]:
b=np.expand_dims(a,axis=1)
print(b.shape)
print(b.ndim)

(6, 1)
2


In [16]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
print(a[a<5])

[1 2 3 4]


In [19]:
five_up=(a>=5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [20]:
divisible_by_2=a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


#### basic operations

In [7]:

data=np.array([1,2])
ones=np.ones(2,dtype=int)
data + ones

array([2, 3])

In [9]:
print(data-ones)
print(data*data)
print(data/data)

[0 1]
[1 4]
[1. 1.]


In [10]:
a=np.array([1,2,3,4])
a.sum()

10

In [12]:
print(a.max())
print(a.min())
print(a.sum())

4
1
10


In [14]:
data=np.array([[1,2],[5,3],[4,6]])
data
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 5 6]


#### stacking

In [21]:
a1=np.array([[1,1],
            [2,2]])
a2=np.array([[3,3],
            [4,4]])             #vertical stacking
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [22]:
np.hstack((a1,a2))          #horizontal stacking

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

#### split

In [23]:
import numpy as np
x=np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [25]:
print(np.hsplit(x,4))

[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4,  5,  6],
       [16, 17, 18]]), array([[ 7,  8,  9],
       [19, 20, 21]]), array([[10, 11, 12],
       [22, 23, 24]])]


In [26]:
np.hsplit(x,(3,5))    #split aftr 3rd and 5th column

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5],
        [16, 17]]),
 array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24]])]

#### creating matrices

In [27]:
data=np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
print(data[0,1])
print(data[1:3])
print(data[0:2,0])

2
[[3 4]
 [5 6]]
[1 3]


In [30]:
data=np.array([[1,2],[3,4],[5,6]])
data
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


#### unique elements

In [31]:
a=np.array([11,11,12,13,14,15,16,17,12,13,11,14,18,19,20])
unique_values=np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [32]:
unique_values,indices_list=np.unique(a,return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [33]:
a_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[1,2,3,4]])
unique_values=np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [34]:
unique_rows=np.unique(a_2d,axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
unique_column=np.unique(a_2d,axis=1)
print(unique_column)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


#### Transpose & reshape

In [36]:
arr=np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [37]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [38]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

#### reverse

In [39]:
arr=np.array([1,2,3,4,5,6,7,8])
reversed_arr=np.flip(arr)
print("Reversed array: ",reversed_arr)

Reversed array:  [8 7 6 5 4 3 2 1]


In [42]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
reversed_arr=np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [45]:
reversed_arr_rows=np.flip(arr_2d,axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [44]:
reversed_arr_columns=np.flip(arr_2d,axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
